version: "3"

services:
  todor:
    image: peterstoychev/todor-reloaded:latest-arm
    container_name: todor
    restart: unless-stopped
    depends_on:
      - lavalink
    volumes:
      - ./config.json:/App/config.json:ro

  lavalink:
    image: ghcr.io/freyacodes/lavalink:3.7.11
    container_name: lavalink
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro